version: '3.8'

services:
  nginx:
    build:
      context: .
    networks:
      - link
      - default
    image: ingress-nginx
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /certs
        read_only: true
    ports:
      - 80:80
      - 443:443

networks:
  link:
    internal: true
