version: '3.8'

services:
  nginx:
    build:
      context: .
    networks:
      - link
      - default
    image: ingress-nginx
    ports:
      - 80:80

networks:
  link:
    internal: true